// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxf0-BFzcI8JS9JHhPjzVdmYTSt9Gq88k',
    appId: '1:776678621580:web:61bf6ed52fa75db5d996a9',
    messagingSenderId: '776678621580',
    projectId: 'myapp-flutter-project-8441e',
    authDomain: 'myapp-flutter-project-8441e.firebaseapp.com',
    storageBucket: 'myapp-flutter-project-8441e.firebasestorage.app',
    measurementId: 'G-LP2YF28X02',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBL0amFCZkjFIyRzulUUVaIv7mYZ0hc4wk',
    appId: '1:776678621580:android:4618f58fd4c82d98d996a9',
    messagingSenderId: '776678621580',
    projectId: 'myapp-flutter-project-8441e',
    storageBucket: 'myapp-flutter-project-8441e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFl-Qg7vmCKhiEf83H9P6ECJHwt1cQLxk',
    appId: '1:776678621580:ios:24d155c67ac08ae4d996a9',
    messagingSenderId: '776678621580',
    projectId: 'myapp-flutter-project-8441e',
    storageBucket: 'myapp-flutter-project-8441e.firebasestorage.app',
    iosBundleId: 'com.leaningapp.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFl-Qg7vmCKhiEf83H9P6ECJHwt1cQLxk',
    appId: '1:776678621580:ios:24d155c67ac08ae4d996a9',
    messagingSenderId: '776678621580',
    projectId: 'myapp-flutter-project-8441e',
    storageBucket: 'myapp-flutter-project-8441e.firebasestorage.app',
    iosBundleId: 'com.leaningapp.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxf0-BFzcI8JS9JHhPjzVdmYTSt9Gq88k',
    appId: '1:776678621580:web:1dc8b6f447d65127d996a9',
    messagingSenderId: '776678621580',
    projectId: 'myapp-flutter-project-8441e',
    authDomain: 'myapp-flutter-project-8441e.firebaseapp.com',
    storageBucket: 'myapp-flutter-project-8441e.firebasestorage.app',
    measurementId: 'G-MDVHSXFWE5',
  );

}